version: '3.8'

services:
  app:
    build: .
    container_name: sportsline-api
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
